docs: Provide worked Kafka example with beam
googleapis/java-pubsublite pull request #323
Opened 2020-10-22 16:35 UTC by dpcollins-google

2020-10-22 17:27 UTC, lesv requested changes
I'll come back to this after my next meeting, I don't see a pom.xml, so I wonder a bit.  Also, it looks like there might be a line length issue.

2020-10-22 17:27 UTC, lesv commented on samples/snippets/src/main/java/pubsublite/kafka/KafkaIOReadExample.java
> +package com.google.cloud.pubsublite.demo;
Shouldn't use `com.google.*` for sample / demo package names.  `com.example.*` or `productname.xxx`

2020-10-22 17:27 UTC, lesv commented on samples/snippets/src/main/java/pubsublite/kafka/KafkaIOReadExample.java
> +package com.google.cloud.pubsublite.demo;
We don't want customers accidently publishing w/ com.google

2020-10-22 17:28 UTC, lesv commented
Ah - I see checkstyle has failed, please fix those issues and then ping me.

2020-12-04 14:47 UTC, dpcollins-google commented
Closing this, it was never intended to be merged.

2020-12-04 14:47 UTC, closed without merging