fix: remove local copy of beam I/O now that it is merged to upstream
googleapis/java-pubsublite pull request #873
Opened 2021-09-13 14:15 UTC by dpcollins-google

2021-09-13 23:05 UTC, anguillanneuf requested changes
- Please also remove `pubsublite-beam-io` from `versions.txt`.
- Is the PubsubLiteIO in Beam version `2.32.0` equivalent to version `0.19.5` here?  If not, we may consider removing the files here after the next Beam release.
- Please also resolve the merge conflicts. Thank you!
- Please also update this JIRA ticket: https://issues.apache.org/jira/browse/BEAM-10114
- (FYI) sample has been updated: https://github.com/GoogleCloudPlatform/java-docs-samples/pull/5312. Docs too. (cl/396653855)

2021-09-15 15:57 UTC, dpcollins-google commented on samples/snapshot/pom.xml
> -    </dependency>
Done.

2021-09-15 15:59 UTC, dpcollins-google commented on pubsublite-beam-io/README.md
> -triggers, or use processing-time triggers instead.
I've left the file with its contents but updated them to be correct for the version that will be released in 2.33.0. Do you want me to leave the text or replace it with a reference as described above?

2021-09-15 16:02 UTC, dpcollins-google commented
> * Please also remove `pubsublite-beam-io` from `versions.txt`.

Done

> * Is the PubsubLiteIO in Beam version `2.32.0` equivalent to version `0.19.5` here?  If not, we may consider removing the files here after the next Beam release.

Version 2.33.0 will be equivalent, I'll add a DO_NOT_MERGE label for now.

> * Please also resolve the merge conflicts. Thank you!

Done

> * Please also update this JIRA ticket: https://issues.apache.org/jira/browse/BEAM-10114

Done

> * (FYI) sample has been updated: [GoogleCloudPlatform/java-docs-samples#5312](https://github.com/GoogleCloudPlatform/java-docs-samples/pull/5312). Docs too. (cl/396653855)

2021-09-15 17:00 UTC, anguillanneuf commented on pubsublite-beam-io/README.md
> -triggers, or use processing-time triggers instead.
We should add the above reference in the top. Keeping your changes means we need to keep it updated. We can do that for the next release and then remove.

2021-11-22 20:04 UTC, dpcollins-google commented on pubsublite-beam-io/README.md
> -triggers, or use processing-time triggers instead.
Done.

2021-11-22 20:14 UTC, manuelmenzella-google approved these changes

2021-11-22 20:16 UTC, merged